### ISSUE TITLE
Broken Link:https://index.ros.org/doc/ros2/Troubleshooting/Installation-Troubleshooting/#import-failing-without-library-present-on-the-system'

### ISSUE THREAD

**Issue by jmtc7** [ros-infrastructure/rosindex#390]
### 404 Page URL

https://index.ros.org/doc/ros2/Troubleshooting/Installation-Troubleshooting/#import-failing-without-library-present-on-the-system'

### Referrer URL

https://index.ros.org/doc/ros2/Troubleshooting/Installation-Troubleshooting/#import-failing-without-library-present-on-the-system

### Description

While installing ROS2 Foxy and trying to test if everything went ok with 'ros2 run demo_nodes_py talker', i got the reported link as suggested help. The traceback:

```
PS C:\> ros2 run demo_nodes_py talker
Traceback (most recent call last):
  File "C:\dev\ros2\lib\demo_nodes_py\talker-script.py", line 33, in <module>
    sys.exit(load_entry_point('demo-nodes-py==0.9.4', 'console_scripts', 'talker')())
  File "C:\dev\ros2\lib\demo_nodes_py\talker-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "C:\Python38\lib\importlib\metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "C:\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\dev\ros2\Lib\site-packages\demo_nodes_py\topics\talker.py", line 16, in <module>
    from rclpy.node import Node
  File "C:\dev\ros2\Lib\site-packages\rclpy\node.py", line 42, in <module>
    from rclpy.client import Client
  File "C:\dev\ros2\Lib\site-packages\rclpy\client.py", line 22, in <module>
    from rclpy.impl.implementation_singleton import rclpy_implementation as _rclpy
  File "C:\dev\ros2\Lib\site-packages\rclpy\impl\implementation_singleton.py", line 31, in <module>
    rclpy_implementation = _import('._rclpy')
  File "C:\dev\ros2\Lib\site-packages\rclpy\impl\__init__.py", line 28, in _import
    return importlib.import_module(name, package='rclpy')
  File "C:\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'rclpy._rclpy'
The C extension 'C:\dev\ros2\Lib\site-packages\rclpy\_rclpy.pyd' isn't present on the system. Please refer to 'https://index.ros.org/doc/ros2/Troubleshooting/Installation-Troubleshooting/#import-failing-without-library-present-on-the-system' for possible solutions
```

**Comment by clalancette** [comment]
Since Foxy is End-of-Life, we won't be updating that URL.  So I'll close this out.
